name: publish
on:
  workflow_dispatch:
    inputs:
      release_as_beta:
        description: "Release as 'beta'"
        required: true
        type: boolean
        default: true
permissions:
  contents: write
  packages: write
  
jobs:
  mod-build:
    name: 📦 Build mod
    runs-on: ubuntu-latest
    outputs:
      archives_base_name: ${{ steps.mod_properties.outputs.archives_base_name }}
      minecraft_version: ${{ steps.mod_properties.outputs.minecraft_version }}
      mod_version: ${{ steps.mod_properties.outputs.mod_version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: mod-build-files
          path: build/libs/
      - name: Read value from Properties-file
        id: mod_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version'
  publish-github:
    name: 🐙 Publish to GitHub
    runs-on: macos-latest
    needs: mod-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4.1.0
        with:
          path: build/
      - name: debug
        run: mv build/mod-build-files build/libs
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar
          github-tag: "v${{ env.mod_version }}-${{ env.mc_version }}"
          name: "v${{ env.mod_version }}-${{ env.mc_version }}"
          version: "v${{ env.mod_version }}-${{ env.mc_version }}"
          version-type: ${{ inputs.release_as_beta && 'beta' || 'release' }}
        env:
          mod_name: ${{ needs.mod-build.outputs.archives_base_name }}
          mc_version: ${{ needs.mod-build.outputs.minecraft_version }}
          mod_version: ${{ needs.mod-build.outputs.mod_version }}
